# Development dockerfile for frontend main app
# Process flow:
#   1. npm ci
#   2. npm run dev

# 1) Download dependencies
FROM node:22-alpine AS dependencies
WORKDIR /frontend-app
COPY package.json package-lock.json ./
RUN npm ci

# 2) Prepare frontend app for dev server
FROM node:22-alpine AS builder
WORKDIR /frontend-app
# All dependency files from 1)
COPY --from=dependencies /frontend-app/node_modules ./node_modules
# Frontend source code
COPY ./src/ ./src/
# Config files required by Next.js dev server
COPY package.json package-lock.json next.config.ts tsconfig.json postcss.config.mjs eslint.config.mjs ./

EXPOSE 3000

CMD ["npm", "run", "dev", "--", "--hostname", "0.0.0.0"]
